### PR TITLE
コンタクトフォームを追加

### PR DESCRIPTION
**Pull request by gpioblink**

### CODE REVIEW

**Comment by aizu-wakamatsu** [comment]
I think it is needed to put contact addresses info on that section.
It's so bad to put just only contact form.

**Comment by gpioblink** [comment]
Who's address you think to put?

**Comment by gpioblink** [comment]
@aizu-wakamatsu Thank you for response. Family Reader?

**Comment by aizu-wakamatsu** [comment]
Leader. not Reader.

**Comment by gpioblink** [comment]
Yeah, I know. But, I don't know our family reader's address.
So, could you please send me the e-mail address?

**Comment by aizu-wakamatsu** [comment]
It's me.

**Comment by gpioblink** [comment]
Tell me your e-mail address

**Comment by ReonNamatame** [comment]
This is a email address to contact me.

reon64.1173@gmail.com

**Comment by Fironn** [comment]
草

**Comment by aizu-wakamatsu** [comment]
my "u-aizu" *e*mail address.

**Comment by gpioblink** [comment]
@ReonNamatame @Fironn @aizu-wakamatsu Thank you for your feedback.
I added @aizu-wakamatsu e-mail address. Please check it.

**Comment by aizu-wakamatsu** [comment]
I confirmed. and I added newline after contact-form.

**Pull request merged**
