### PR TITLE
Made draft

### PR DESCRIPTION
**Pull request by 0eta0**
こんな感じでどう？

### CODE REVIEW

**Comment by aizu-wakamatsu** [comment]
Checked

**Comment by gpioblink** [comment]
よい

**Comment by aizu-wakamatsu** [comment]
Tari at line 9

**Comment by 0eta0** [comment]
@aizu-wakamatsu 
Could you fix it? then commit and push on this branch.

**Comment by aizu-wakamatsu** [comment]
I fixed that problem then committed and pushed. This is just a Japanese linguistic problem.
Please see the reference website (https://www.nhk.or.jp/bunken/summary/kotoba/gimon/154.html).

**Comment by 0eta0** [comment]
OK, thank you.
Can I merge this branch to draft?

**Comment by aizu-wakamatsu** [comment]
I confirmed the merged branch. Thank you for improving the quality of this article.

**Pull request merged**
